import { FaInfoCircle } from 'react-icons/fa';
import styles from './ForecastCard.module.scss';
import { Dropdown, Table, Tabs } from 'shared-ui';
import { forecastMock } from '../mock';
import dayjs from 'dayjs';
import { Tooltip } from 'react-tooltip';
import { useState } from 'react';
import { ForecastChart } from './ForecastChart';
import { Forecast } from '../../../_services/overview.service';
import Skeleton from 'react-loading-skeleton';

type Props = {
  data?: Forecast;
  loading: boolean;
};

const chartModes = [
  {
    label: 'Revenue',
    value: 'revenue',
  },
  {
    label: 'Profit',
    value: 'profit',
  },
];

//TODO: Vertical table (header = days)
export const ForecastCard = (props: Props) => {
  const [selectedMode, setSelectedMode] = useState(0);
  const [selectedChartMode, setSelectedChartMode] = useState<
    'revenue' | 'profit'
  >('revenue');

  return (
    <>
      <div className={styles.card}>
        <div className={styles.header}>
          <div>
            <h2 className={styles.title}>Forecast</h2>
            <Tabs
              tabs={['Table', 'Chart']}
              onClick={setSelectedMode}
              selectedIndex={selectedMode}
              className={styles.tabs}
            />
          </div>
          <div className={styles.rightHeader}>
            {selectedMode === 1 && (
              <Dropdown
                options={chartModes}
                selectedOption={selectedChartMode}
                onOptionChange={(value) =>
                  setSelectedChartMode(value as 'revenue' | 'profit')
                }
              />
            )}
            <FaInfoCircle
              data-tooltip-id="forecast-tooltip"
              data-tooltip-content="These data generated by Peckish are forecasts of future performance"
            />
          </div>
        </div>
        <div className={styles.content}>
          {/* {Children} */}
          {selectedMode === 0 ? (
            props.loading ? (
              <ForecastTableSkeleton />
            ) : (
              <Table
                data={props.data}
                columns={[
                  {
                    header: 'Date',
                    key: 'date',
                    renderItem: (row) => dayjs(row.date).format('ddd D'),
                  },
                  // occupancy
                  // sales
                  { header: 'Occupancy', key: 'occupancy' },
                  { header: 'Sales', key: 'sales' },
                  { header: 'Profit', key: 'profit' },
                  { header: 'Savings', key: 'savings' },
                ]}
              />
            )
          ) : (
            <ForecastChart
              data={props.data}
              visibleMetric={selectedChartMode}
            />
          )}
        </div>
      </div>

      <Tooltip id="forecast-tooltip" />
    </>
  );
};

const ForecastTableSkeleton = () => {
  const renderItem = () => <Skeleton width={50} />;

  return (
    <Table
      data={[...Array(7)].map<Forecast[number]>((_, i) => ({
        date: dayjs().add(i, 'day').toDate(),
        occupancy: 0,
        profit: 0,
        sales: 0,
        savings: 0,
      }))}
      columns={[
        {
          header: 'Date',
          key: 'date',
          renderItem: (row) => dayjs(row.date).format('ddd D'),
        },
        // occupancy
        // sales
        { header: 'Occupancy', key: 'occupancy', renderItem },
        { header: 'Sales', key: 'sales', renderItem },
        { header: 'Profit', key: 'profit', renderItem },
        { header: 'Savings', key: 'savings', renderItem },
      ]}
    />
  );
};
